// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upbdokcjqhcfyvqxbakb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwYmRva2NqcWhjZnl2cXhiYWtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNjkwOTgsImV4cCI6MjA2Mjk0NTA5OH0.W2HXej-zojzrH0VhmWvlNuFFWyCmoCIhzDf49FjXUBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);